name: automation-exercise
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: "Install style checker"
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
      - name: "Run tests"
        run: pytest
      - name: "Run coverage"
        run: coverage run -m pytest
      - name: "Upload coverage artifact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage/
